"""Türkçe Chat Kısaltmaları ve Günlük Konuşma Genişletici (Slang Expander).
Discord, Instagram, WhatsApp ve oyun sohbetlerinde sıkça geçen kısaltmaları ve
ağız/günlük konuşma kalıplarını standart Türkçeye dönüştürür.
"""

from src.turkish_case import turkish_lower
from typing import Optional

CHAT_SLANG_MAP = {
    # --- Günlük Konuşma, Kalıplar ve Soru İfadeleri ---
    "bune": "bu ne",
    "şune": "şu ne",
    "sune": "şu ne",
    "one": "o ne",
    "noluor": "ne oluyor",
    "noluyo": "ne oluyor",
    "noluyor": "ne oluyor",
    "noldu": "ne oldu",
    "nolcak": "ne olacak",
    "nolucak": "ne olacak",
    "niden": "neden",
    "niye": "niye",
    "niyki": "iyi ki",
    "iyiki": "iyi ki",
    "hersey": "her şey",
    "herşey": "her şey",
    "herkez": "herkes",
    "herkes": "herkes",
    "bişey": "bir şey",
    "bisey": "bir şey",
    "birsey": "bir şey",
    "birşey": "bir şey",
    "hiçbirşey": "hiçbir şey",
    "hicbirsey": "hiçbir şey",
    "bisi": "bir şey",
    "bişi": "bir şey",
    "hicbi": "hiçbir",
    "hicbir": "hiçbir",
    "hiçbi": "hiçbir",
    "hicbisi": "hiçbir şey",
    "hiçbişi": "hiçbir şey",

    # --- Konum & Bulunma Bildiren Günlük Kelimeler ---
    "içerdeyim": "içerideyim",
    "icerdeyim": "içerideyim",
    "içerde": "içeride",
    "icerde": "içeride",
    "dışardayım": "dışarıdayım",
    "disardayim": "dışarıdayım",
    "dışarda": "dışarıda",
    "disarda": "dışarıda",
    "yukardayım": "yukarıdayım",
    "yukardayim": "yukarıdayım",
    "yukarda": "yukarıda",
    "aşağdayım": "aşağıdayım",
    "aşağda": "aşağıda",
    "asagida": "aşağıda",
    "burdayım": "buradayım",
    "burdayim": "buradayım",
    "burda": "burada",
    "şurdayım": "şuradayım",
    "surdayim": "şuradayım",
    "şurda": "şurada",
    "surda": "şurada",
    "ordayım": "oradayım",
    "ordayim": "oradayım",
    "orda": "orada",

    # --- Doldurma Kelimeleri (fln, falan, vb) ---
    "fln": "falan",
    "flan": "falan",
    "flnsal": "falansal",
    "falansal": "falansal",
    "filan": "falan",
    "vb": "ve benzeri",
    "vs": "ve benzeri",
    "v.b": "ve benzeri",
    "v.s": "ve benzeri",
    "aynn": "aynen",
    "ayn": "aynen",

    # --- Selamlaşma & Vedalaşma & Nezaket ---
    "slm": "selam",
    "mrb": "merhaba",
    "meraba": "merhaba",
    "nbr": "naber",
    "knk": "kanka",
    "kank": "kanka",
    "krdş": "kardeş",
    "krds": "kardeş",
    "tsk": "teşekkürler",
    "tşk": "teşekkürler",
    "tskler": "teşekkürler",
    "tşkler": "teşekkürler",
    "thx": "teşekkürler",
    "eyw": "eyvallah",
    "eyv": "eyvallah",
    "hg": "hoş geldin",
    "hb": "hoş bulduk",
    "kib": "kendine iyi bak",
    "a.s": "aleyküm selam",
    "as": "aleyküm selam",
    "s.a": "selamün aleyküm",
    "sa": "selamün aleyküm",
    "bb": "bay bay",
    "by": "bay bay",
    "bye": "bay bay",
    "byebye": "bay bay",
    "tmm": "tamam",
    "tm": "tamam",
    "ok": "tamam",
    "oki": "tamam",
    "oke": "tamam",
    "okey": "tamam",
    "peki": "peki",
    "rica": "rica ederim",
    "ö.d": "önemli değil",
    "od": "önemli değil",
    "onemli degil": "önemli değil",
    "hyr": "hayır",
    "evt": "evet",
    "nys": "neyse",
    "snrm": "sanırım",
    "glba": "galiba",
    "bence": "bence",
    "sence": "sence",
    "acaba": "acaba",
    "tabi": "tabii",
    "tabiki": "tabii ki",
    "tabikide": "tabii ki de",

    # --- Sık Kullanılan Fiil / Eylem Kısaltmaları ---
    "napion": "ne yapıyorsun",
    "napiyon": "ne yapıyorsun",
    "napıyon": "ne yapıyorsun",
    "napıyosun": "ne yapıyorsun",
    "napiyosun": "ne yapıyorsun",
    "naptin": "ne yaptın",
    "naptın": "ne yaptın",
    "naptiniz": "ne yaptınız",
    "naptınız": "ne yaptınız",
    "napim": "ne yapayım",
    "napayım": "ne yapayım",
    "napcan": "ne yapacaksın",
    "napıcaksın": "ne yapacaksın",
    "napicaksin": "ne yapacaksın",
    "napıonuz": "ne yapıyorsunuz",
    "napiyonuz": "ne yapıyorsunuz",
    "gelcenmi": "gelecek misin",
    "geliyonmu": "geliyor musun",
    "gidiyonmu": "gidiyor musun",
    "geliyomusun": "geliyor musun",
    "gidiyomusun": "gidiyor musun",
    "geliyormusun": "geliyor musun",
    "gidiyormusun": "gidiyor musun",
    "iyimisin": "iyi misin",
    "iyimisiniz": "iyi misiniz",
    "yapiyonmu": "yapıyor musun",
    "yapıyonmu": "yapıyor musun",
    "girekmi": "girelim mi",
    "girelimmi": "girelim mi",
    "oynakmi": "oynayalım mı",
    "oynayalimmi": "oynayalım mı",
    "atakmi": "atalım mı",
    "atalimmi": "atalım mı",
    "gidelimmi": "gidelim mi",
    "yapalimmi": "yapalım mı",
    "gelekmi": "gelelim mi",
    "yayindamisin": "yayında mısın",
    "yayındamısın": "yayında mısın",
    "oyundamisin": "oyunda mısın",
    "oyundamısın": "oyunda mısın",
    "dcydemisin": "dc'de misin",
    "dcdemisin": "dc'de misin",
    "burdamisin": "burada mısın",
    "burdamısın": "burada mısın",
    "ordamisin": "orada mısın",
    "ordamısın": "orada mısın",
    "evdemisin": "evde misin",
    "uyudunmu": "uyudun mu",
    "yattinmi": "yattın mı",
    "yattınmı": "yattın mı",
    "kalktinmi": "kalktın mı",
    "kalktınmı": "kalktın mı",
    "yazamiom": "yazamıyorum",
    "yazamıyom": "yazamıyorum",
    "yapamiom": "yapamıyorum",
    "yapamıyom": "yapamıyorum",
    "gidemiom": "gidemiyorum",
    "gidemiyom": "gidemiyorum",
    "gelemiom": "gelemiyorum",
    "gelemiyom": "gelemiyorum",
    "bilmiom": "bilmiyorum",
    "bilmiyom": "bilmiyorum",
    "istemiom": "istemiyorum",
    "istemiyom": "istemiyorum",
    "anlamiom": "anlamıyorum",
    "anlamıyom": "anlamıyorum",
    "gorüşürüz": "görüşürüz",
    "gorusuruz": "görüşürüz",
    "geliyom": "geliyorum",
    "gidiyom": "gidiyorum",
    "geliyo": "geliyor",
    "gidiyo": "gidiyor",
    "yapıyo": "yapıyor",
    "yapiyo": "yapıyor",
    "oluyo": "oluyor",
    "biliyo": "biliyor",
    "bakiom": "bakıyorum",
    "bakıyom": "bakıyorum",
    "bekliom": "bekliyorum",
    "bekliyom": "bekliyorum",
    "özledim": "özledim",
    "ozledim": "özledim",

    # --- Zaman & Bağlaç Kısaltmaları ---
    "zmn": "zaman",
    "nezaman": "ne zaman",
    "şimdi": "şimdi",
    "simdi": "şimdi",
    "sora": "sonra",
    "soraan": "sonradan",
    "azora": "az sonra",
    "bi": "bir",
    "bida": "bir daha",
    "bidaha": "bir daha",
    "tekra": "tekrar"
}

def expand_slang(token: str) -> Optional[str]:
    """Kısaltma veya chat argo kelimesini tam Türkçe karşılığına açar."""
    return CHAT_SLANG_MAP.get(turkish_lower(token))
